version: "3"

services:
  db:
    container_name: sbm-db
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h db -p 5432"]
      interval: 1s
      timeout: 5s
      retries: 2
    env_file:
      - .env
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio-sbm
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network

  backend:
    container_name: sbm-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY_ID=minioadmin
      - MINIO_SECRET_ACCESS_KEY=minioadmin
      - DATABASE_URL=postgresql://admin:admin@db:5432/sbmdb?schema=public
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:

volumes:
  minio-data:
    driver: local